version: '3.1'

# Run proxy server and Total.js Code
services:

  code:
    container_name: code
    image: totalplatform/code
    restart: always
    volumes:
      - codedata:/databases
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /www/www/:/www/www                    # Edit development folder
    environment:
      - FOLDER_WWW=/www/www/                  # Edit development folder
      - FOLDER_NPM=/www/node_modules/         # Edit node_modules folder
      - LETSENCRYPT_HOST=code.youdomain.com
      - VIRTUAL_HOST=code.youdomain.com
      - VIRTUAL_PORT=8000
      - VIRTUAL_MAX_UPLOAD=100
      - HTTPS_METHOD=redirect
      - DISABLE_ACCESS_LOGS=1

volumes:
  codedata:

networks:
  default:
    name: proxy
    external: true