version: '3.1'

# Run proxy server and Total.js Code
services:

  code:
    container_name: code
    image: totalplatform/code
    restart: always
    volumes:
      - codedata:/code/databases
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /yourlocalpath/:/www/www                    # Edit development folder
    environment:
      - UID=code                                    # A custom code ID
      - FOLDER_WWW=/yourlocalpath/                  # Edit development folder
      - FOLDER_NPM=/yourlocalpath/node_modules/     # Edit node_modules folder
      # - ORIGIN=https://{0}.abc.eu.totaljs.cloud     # A custom origin due to URL restrictions
      - LETSENCRYPT_HOST=code.youdomain.com
      - VIRTUAL_HOST=code.youdomain.com
      - VIRTUAL_PORT=8000
      - VIRTUAL_MAX_UPLOAD=100
      - HTTPS_METHOD=redirect
      - DISABLE_ACCESS_LOGS=1

volumes:
  codedata:

networks:
  default:
    name: proxy
    external: true